version: '3.8'

services:
  web:
    build: .
    container_name: oauth2-playground-web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - oauth2-network

networks:
  oauth2-network:
    driver: bridge
